### ISSUE TITLE
IPv6 address run on server

### ISSUE THREAD

**Issue by dokser** [alpine-sec/SPECTR3#1] opened 2024-09-23 12:17 UTC
Hi. When I run the SPECTR3 on inspected Windows mashine, I see only IPv6 address . After the cancelation of IPv6 address in adapter settings, I see only next 0.0.0.0 address and 3262 port.
When is my inspected Windows mashine IPv4 address?  Why I can't see them. I can't found sharing scsi volume in local network. Help, understand what I need to do. Thank.

**Comment by kero99** [comment] 2024-09-24 07:51
Hi @dokser , I don't know if I understand very well where the problem is, could you send me a screenshot with spectr3 running and the ip of the machine? Something like this:

![image](https://github.com/user-attachments/assets/14e438f9-0e5f-47b1-8904-05a90ae5f513)

**Comment by dokser** [comment] 2024-09-24 08:03
Thanks for your response. I will send you a Pictures. ![20240924_110002.jpg](https://github.com/user-attachments/assets/3221b289-aca2-4b16-a9c1-61d5491bdbec)

![20240924_105942.jpg](https://github.com/user-attachments/assets/c29d68ce-9b9e-4e05-a237-dc91c1852825)

You can see a real ipv6 address on  my Network adapter settings. And cmd screenshot of Spectr3 running program.

**Comment by kero99** [comment] 2024-09-24 12:29
Ok, clear now .I will try to explain:

![image](https://github.com/user-attachments/assets/3fc618ca-67cc-4326-b7b7-0994ed364aac)

The marked as 1, is the address in which the iscsi volume is published, in this case, having ipv6 active, has caught that address, but this line is only helpful, you can use the ipv4 of your computer in the second screenshot appears as 10.0.0.13

What is marked as 2, is the binding, 0.0.0.0.0 means that the connection is accepted from any ip with connection to the machine.

![image](https://github.com/user-attachments/assets/745dfa0d-679b-4786-88bb-c4a9f7c5aaf8)

Use your favorite iscsi initiator to connect to 10.0.0.13:3262 and you are done =)

**Comment by dokser** [comment] 2024-09-24 13:45
Thanks

**Closed as completed** 2024-09-27 17:31 UTC
